import type { PracticeSeed } from "./types";

/**
 * Practices aimed at mental state. Most are deliberately `discreet: true` and
 * SEATED -- the whole point is that they work in an open office or on a call,
 * which is exactly when a desk worker needs them.
 */
export const mentalPractices: PracticeSeed[] = [
  // --- Breathwork ---
  {
    slug: "physiological-sigh",
    name: "Physiological Sigh",
    description: "The fastest reliable way to drop your stress level in under a minute.",
    instructions:
      "Inhale through your nose, then take a second short sip of air on top of it. Let it all out slowly through your mouth with a long sigh. Repeat five times.",
    difficulty: "BEGINNER",
    durationSeconds: 40,
    equipment: "none",
    goals: ["REDUCE_STRESS"],
    modality: "BREATHWORK",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    breathPattern: "2-0-6",
    mechanisms: [
      { slug: "parasympathetic-downshift", weight: 95 },
      { slug: "diaphragm", weight: 70 },
    ],
  },
  {
    slug: "box-breathing",
    name: "Box Breathing",
    description: "An even, four-count rhythm that steadies a racing mind.",
    instructions:
      "Breathe in for four counts, hold for four, out for four, hold for four. Keep the corners of the box even. Continue for the full round.",
    difficulty: "BEGINNER",
    durationSeconds: 60,
    equipment: "none",
    goals: ["REDUCE_STRESS", "IMPROVE_FOCUS"],
    modality: "BREATHWORK",
    posture: "SEATED",
    discreet: true,
    exertion: 1,
    breathPattern: "4-4-4-4",
    mechanisms: [
      { slug: "parasympathetic-downshift", weight: 85 },
      { slug: "attention-control", weight: 60 },
      { slug: "diaphragm", weight: 60 },
    ],
  },
  {
    slug: "extended-exhale",
    name: "Extended Exhale",
    description: "Lengthening the out-breath tips you toward rest-and-digest.",
    instructions:
      "Breathe in through your nose for four counts. Breathe out slowly for eight, as if through a straw. Let your shoulders drop on every exhale.",
    difficulty: "BEGINNER",
    durationSeconds: 50,
    equipment: "none",
    goals: ["REDUCE_STRESS"],
    modality: "BREATHWORK",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    breathPattern: "4-0-8",
    mechanisms: [
      { slug: "parasympathetic-downshift", weight: 90 },
      { slug: "diaphragm", weight: 75 },
    ],
  },
  {
    slug: "coherent-breathing",
    name: "Coherent Breathing",
    description: "A slow, even six-second rhythm that settles heart rate variability.",
    instructions:
      "Breathe in for six counts and out for six, with no pause at either end. Keep it smooth and quiet. Let the rhythm do the work.",
    difficulty: "BEGINNER",
    durationSeconds: 60,
    equipment: "none",
    goals: ["REDUCE_STRESS", "LIFT_MOOD"],
    modality: "BREATHWORK",
    posture: "SEATED",
    discreet: true,
    exertion: 1,
    breathPattern: "6-0-6",
    mechanisms: [
      { slug: "parasympathetic-downshift", weight: 80 },
      { slug: "diaphragm", weight: 80 },
      { slug: "interoception", weight: 45 },
    ],
  },
  {
    slug: "energizing-breath",
    name: "Energizing Breath",
    description: "Short, brisk breaths that lift alertness without caffeine.",
    instructions:
      "Sit tall. Take twenty quick, light breaths in and out through your nose, keeping the belly soft. Then one slow, full breath to finish.",
    difficulty: "BEGINNER",
    durationSeconds: 40,
    equipment: "none",
    goals: ["ENERGY", "IMPROVE_FOCUS"],
    modality: "BREATHWORK",
    posture: "SEATED",
    discreet: false,
    exertion: 2,
    breathPattern: "1-0-1",
    mechanisms: [
      { slug: "sympathetic-upshift", weight: 90 },
      { slug: "diaphragm", weight: 60 },
    ],
  },
  {
    slug: "belly-breathing",
    name: "Belly Breathing",
    description: "Re-teaches the diaphragm to do the work instead of the neck and chest.",
    instructions:
      "Rest one hand on your belly. Breathe in so that hand moves out while your chest stays still. Breathe out slowly and feel it fall.",
    difficulty: "BEGINNER",
    durationSeconds: 50,
    equipment: "none",
    goals: ["REDUCE_STRESS", "PREVENT"],
    modality: "BREATHWORK",
    posture: "SEATED",
    discreet: true,
    exertion: 1,
    breathPattern: "4-1-6",
    mechanisms: [
      { slug: "diaphragm", weight: 95 },
      { slug: "parasympathetic-downshift", weight: 65 },
      { slug: "interoception", weight: 50 },
    ],
  },

  // --- Gaze / visual ---
  {
    slug: "twenty-twenty-twenty",
    name: "20-20-20 Look Away",
    description: "The standard reset for eyes locked at screen distance.",
    instructions:
      "Find something at least twenty feet away — out a window if you can. Rest your gaze on it softly for twenty seconds. Blink normally.",
    difficulty: "BEGINNER",
    durationSeconds: 30,
    equipment: "none",
    goals: ["PREVENT", "IMPROVE_FOCUS"],
    modality: "GAZE",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [{ slug: "visual-system", weight: 95 }],
  },
  {
    slug: "near-far-focus",
    name: "Near-Far Focus",
    description: "Works the focusing muscles that hold one distance all day.",
    instructions:
      "Hold a thumb up at arm's length. Focus on it, then shift to something far away, then back. Move slowly and let each one come fully sharp.",
    difficulty: "BEGINNER",
    durationSeconds: 40,
    equipment: "none",
    goals: ["MOBILITY", "PREVENT"],
    modality: "GAZE",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [{ slug: "visual-system", weight: 90 }],
  },
  {
    slug: "palming",
    name: "Palming",
    description: "Complete darkness for tired eyes, and a pause for everything behind them.",
    instructions:
      "Rub your palms together until warm. Cup them gently over your closed eyes without pressing. Rest in the dark and breathe slowly.",
    difficulty: "BEGINNER",
    durationSeconds: 45,
    equipment: "none",
    goals: ["REDUCE_PAIN", "REDUCE_STRESS"],
    modality: "GAZE",
    posture: "SEATED",
    discreet: false,
    exertion: 1,
    mechanisms: [
      { slug: "visual-system", weight: 85 },
      { slug: "parasympathetic-downshift", weight: 50 },
    ],
  },
  {
    slug: "peripheral-vision-widen",
    name: "Widen Your Vision",
    description: "Releasing tunnel vision releases the alertness state that goes with it.",
    instructions:
      "Look straight ahead and soften your focus. Without moving your eyes, notice what is at the far edges of your vision — above, below, both sides.",
    difficulty: "BEGINNER",
    durationSeconds: 35,
    equipment: "none",
    goals: ["REDUCE_STRESS"],
    modality: "GAZE",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "visual-system", weight: 70 },
      { slug: "parasympathetic-downshift", weight: 70 },
    ],
  },

  // --- Somatic ---
  {
    slug: "jaw-and-face-release",
    name: "Jaw & Face Release",
    description: "Most desk stress collects in the jaw before you ever notice it.",
    instructions:
      "Let your teeth part slightly and your tongue rest heavy. Scrunch your whole face tight for three seconds, then let it all go slack. Repeat.",
    difficulty: "BEGINNER",
    durationSeconds: 35,
    equipment: "none",
    goals: ["REDUCE_STRESS", "REDUCE_PAIN"],
    modality: "SOMATIC",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "parasympathetic-downshift", weight: 70 },
      { slug: "neck-flexors", weight: 45 },
    ],
  },
  {
    slug: "progressive-muscle-release",
    name: "Tense & Release",
    description: "Deliberately tensing a muscle lets it release further than it would alone.",
    instructions:
      "Working upward from your feet, squeeze one muscle group hard for five seconds, then release completely and notice the difference. Move up the body.",
    difficulty: "BEGINNER",
    durationSeconds: 60,
    equipment: "none",
    goals: ["REDUCE_STRESS", "REDUCE_PAIN"],
    modality: "SOMATIC",
    posture: "SEATED",
    discreet: true,
    exertion: 2,
    mechanisms: [
      { slug: "parasympathetic-downshift", weight: 80 },
      { slug: "interoception", weight: 65 },
    ],
  },
  {
    slug: "body-scan-quick",
    name: "Quick Body Scan",
    description: "Find where you are gripping without meaning to.",
    instructions:
      "Start at the top of your head and move your attention slowly down. Wherever you find tension, breathe into it once and let it soften.",
    difficulty: "BEGINNER",
    durationSeconds: 60,
    equipment: "none",
    goals: ["REDUCE_STRESS", "PREVENT"],
    modality: "MINDFULNESS",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "interoception", weight: 95 },
      { slug: "parasympathetic-downshift", weight: 60 },
    ],
  },
  {
    slug: "grounding-five-senses",
    name: "Five Senses Grounding",
    description: "Pulls a spiralling mind back into the room you are actually in.",
    instructions:
      "Name five things you can see, four you can hear, three you can feel, two you can smell, one you can taste. Take your time on each.",
    difficulty: "BEGINNER",
    durationSeconds: 60,
    equipment: "none",
    goals: ["REDUCE_STRESS"],
    modality: "MINDFULNESS",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "interoception", weight: 80 },
      { slug: "attention-control", weight: 75 },
      { slug: "cognitive-reframe", weight: 50 },
    ],
  },
  {
    slug: "self-hug-squeeze",
    name: "Self-Hug Squeeze",
    description: "Deep pressure is a fast, physical signal of safety.",
    instructions:
      "Cross your arms and hold your opposite shoulders. Squeeze firmly and steadily for a slow count of ten, breathing out as you press. Release slowly.",
    difficulty: "BEGINNER",
    durationSeconds: 30,
    equipment: "none",
    goals: ["REDUCE_STRESS", "LIFT_MOOD"],
    modality: "SOMATIC",
    posture: "ANY",
    discreet: false,
    exertion: 1,
    mechanisms: [
      { slug: "parasympathetic-downshift", weight: 75 },
      { slug: "interoception", weight: 55 },
    ],
  },
  {
    slug: "hand-warming",
    name: "Hand Warming",
    description: "Cold hands are a stress signature; warming them reverses it.",
    instructions:
      "Rest your hands in your lap, palms up. Breathe slowly and put your attention entirely on your fingertips, imagining warmth spreading into them.",
    difficulty: "BEGINNER",
    durationSeconds: 45,
    equipment: "none",
    goals: ["REDUCE_STRESS"],
    modality: "SOMATIC",
    posture: "SEATED",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "parasympathetic-downshift", weight: 80 },
      { slug: "interoception", weight: 60 },
    ],
  },

  // --- Motor discharge / energy ---
  {
    slug: "shake-it-out",
    name: "Shake It Out",
    description: "Discharges the wired, fidgety residue of sitting still too long.",
    instructions:
      "Stand up. Shake out your hands, then your arms, then each leg, then your whole body. Keep it loose and let it get slightly ridiculous.",
    difficulty: "BEGINNER",
    durationSeconds: 40,
    equipment: "none",
    goals: ["ENERGY", "REDUCE_STRESS"],
    modality: "MOVEMENT",
    posture: "STANDING",
    discreet: false,
    exertion: 3,
    mechanisms: [
      { slug: "motor-discharge", weight: 95 },
      { slug: "sympathetic-upshift", weight: 55 },
    ],
  },
  {
    slug: "desk-march",
    name: "Desk March",
    description: "Gets blood moving again after a long seated block.",
    instructions:
      "Stand and march on the spot, lifting each knee to hip height. Swing your arms. Keep a steady, brisk pace for the full interval.",
    difficulty: "BEGINNER",
    durationSeconds: 45,
    equipment: "none",
    goals: ["ENERGY"],
    modality: "MOVEMENT",
    posture: "STANDING",
    discreet: false,
    exertion: 3,
    mechanisms: [
      { slug: "sympathetic-upshift", weight: 90 },
      { slug: "motor-discharge", weight: 70 },
      { slug: "hip-flexors", weight: 50 },
    ],
  },
  {
    slug: "power-posture-reset",
    name: "Power Posture Reset",
    description: "Opening the chest and standing tall measurably shifts how you feel.",
    instructions:
      "Stand, plant your feet wide, roll your shoulders back and down, and lift your chest. Hold it and breathe slowly. Resist the urge to shrink back in.",
    difficulty: "BEGINNER",
    durationSeconds: 40,
    equipment: "none",
    goals: ["LIFT_MOOD", "ENERGY"],
    modality: "SOMATIC",
    posture: "STANDING",
    discreet: false,
    exertion: 2,
    mechanisms: [
      { slug: "chest", weight: 70 },
      { slug: "sympathetic-upshift", weight: 65 },
      { slug: "upper-back", weight: 55 },
    ],
  },
  {
    slug: "seated-fidget-release",
    name: "Seated Fidget Release",
    description: "Burns off restlessness without standing up or drawing attention.",
    instructions:
      "Under the desk, press both feet hard into the floor for five seconds, then release. Then press your palms together hard, and release. Alternate.",
    difficulty: "BEGINNER",
    durationSeconds: 35,
    equipment: "none",
    goals: ["REDUCE_STRESS", "ENERGY"],
    modality: "SOMATIC",
    posture: "SEATED",
    discreet: true,
    exertion: 2,
    mechanisms: [
      { slug: "motor-discharge", weight: 85 },
      { slug: "interoception", weight: 40 },
    ],
  },

  // --- Attention / cognitive ---
  {
    slug: "single-point-focus",
    name: "Single-Point Focus",
    description: "A short rep of pure attention control before a block of deep work.",
    instructions:
      "Pick one small object. Rest your full attention on it. When your mind wanders — it will — bring it back without judgement. That return is the rep.",
    difficulty: "BEGINNER",
    durationSeconds: 60,
    equipment: "none",
    goals: ["IMPROVE_FOCUS"],
    modality: "MINDFULNESS",
    posture: "SEATED",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "attention-control", weight: 95 },
      { slug: "visual-system", weight: 40 },
    ],
  },
  {
    slug: "one-thing-next",
    name: "Name the Next One Thing",
    description: "Cuts an overwhelming pile down to the single next action.",
    instructions:
      "Say out loud, or write down, the one thing you will do next. Not the project — the next concrete action. Everything else can wait its turn.",
    difficulty: "BEGINNER",
    durationSeconds: 40,
    equipment: "none",
    goals: ["IMPROVE_FOCUS", "REDUCE_STRESS"],
    modality: "COGNITIVE",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "cognitive-reframe", weight: 90 },
      { slug: "attention-control", weight: 70 },
    ],
  },
  {
    slug: "worry-postpone",
    name: "Park the Worry",
    description: "Deliberately deferring a worry works better than trying not to have it.",
    instructions:
      "Name the worry in one sentence. Decide a specific later time you will think about it properly. Tell yourself it is parked until then, and return to work.",
    difficulty: "BEGINNER",
    durationSeconds: 45,
    equipment: "none",
    goals: ["REDUCE_STRESS"],
    modality: "COGNITIVE",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "cognitive-reframe", weight: 95 },
      { slug: "attention-control", weight: 55 },
    ],
  },
  {
    slug: "three-good-things",
    name: "Three Good Things",
    description: "A fast, evidence-backed lift for a flat mood.",
    instructions:
      "Bring to mind three things that went even slightly well today, however small. For each one, pause long enough to actually feel it before moving on.",
    difficulty: "BEGINNER",
    durationSeconds: 50,
    equipment: "none",
    goals: ["LIFT_MOOD"],
    modality: "COGNITIVE",
    posture: "ANY",
    discreet: true,
    exertion: 1,
    mechanisms: [
      { slug: "cognitive-reframe", weight: 90 },
      { slug: "sympathetic-upshift", weight: 35 },
    ],
  },
  {
    slug: "attention-reset-count",
    name: "Breath Counting Reset",
    description: "Clears a foggy head by giving attention one simple job.",
    instructions:
      "Count each exhale, one through ten, then start again. If you lose count, simply begin at one. Losing count is expected, not failure.",
    difficulty: "BEGINNER",
    durationSeconds: 60,
    equipment: "none",
    goals: ["IMPROVE_FOCUS"],
    modality: "MINDFULNESS",
    posture: "SEATED",
    discreet: true,
    exertion: 1,
    breathPattern: "4-0-6",
    mechanisms: [
      { slug: "attention-control", weight: 90 },
      { slug: "diaphragm", weight: 50 },
      { slug: "parasympathetic-downshift", weight: 45 },
    ],
  },
];
